#define TAPPING_TERM 180

#define AUTO_SHIFT_MODIFIERS
#define AUTO_SHIFT_TIMEOUT TAPPING_TERM
#define NO_AUTO_SHIFT_ALPHA

#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM_PER_KEY

#define RETRO_TAPPING
#define RETRO_TAPPING_PER_KEY

#define IGNORE_MOD_TAP_INTERRUPT